version: '3.9'

services:
  mysql:
    image: 'mysql:8.2.0'
    ports:
      - '3306:3306'
    container_name: payment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: payment
      MYSQL_USER: noah
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mysql-data:
