services:
  mysql:
    image: 'mysql:8.2.0'
    ports:
      - '3306:3306'
    container_name: payment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: payment
      MYSQL_USER: noah
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
